#!/bin/bash

# Load common
source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/common

# Configure versions


PYTHON_VERSION="2.7.6"

# Setup dir references
#PYTHON_DIR="$OPENSHIFT_DATA_DIR/python"
#VIRTUALENV_DIR="$OPENSHIFT_DATA_DIR/venv"
#NGINX_DIR="$OPENSHIFT_DATA_DIR/nginx"
#UWSGI_DIR="$OPENSHIFT_DATA_DIR/uwsgi"

ROOT_DIR=${OPENSHIFT_RUNTIME_DIR}
BUILD_DIR=${OPENSHIFT_TMP_DIR}/build
CONFIG_DIR=${OPENSHIFT_DIY_DIR}/conf
TEMPLATE_DIR=${OPENSHIFT_REPO_DIR}/.openshift/tmpl

REQUIREMENTS_FILE="$OPENSHIFT_REPO_DIR/requirements.txt"
#TEMPLATES_DIR="$OPENSHIFT_REPO_DIR/misc/templates"

# Try to guess the number of processors from /proc/cpuinfo.
if [ -f /proc/cpuinfo ]; then
    NUMBER_OF_PROCESSORS=$(grep -c ^processor /proc/cpuinfo)
else
    NUMBER_OF_PROCESSORS=1
fi

# Load functions
source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/build_python
source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/build_uwsgi

# check python
check_python
# virtual env
check_venv
# virtual uwsgi
check_uwsgi
# install requirement
install_requirements
