#!/bin/bash
function install_mdbtool()
{
    # build mdbtool
    mkdir -p ${BUILD_DIR}
    pushd ${BUILD_DIR}
    rm -rf mdbtools
    git clone https://github.com/wj1918/mdbtools.git 
    cd mdbtools
    export ACLOCAL_PATH=`aclocal --print-ac-dir`:${ROOT_DIR}/libs/share/aclocal
    ${ROOT_DIR}/libs/bin/libtoolize
    autoreconf -i -f
    ./configure --disable-gmdb2 --disable-scrollkeeper --disable-man --prefix=${ROOT_DIR}/libs/
    make
    make install
    popd

}
function install_glib2()
{
    # build 
    mkdir -p ${BUILD_DIR}
    pushd ${BUILD_DIR}
    rm -rf glib-2.42.0
    wget http://ftp.gnome.org/pub/GNOME/sources/glib/2.42/glib-2.42.0.tar.xz 
    tar xvf glib-2.42.0.tar.xz
    pushd glib-2.42.0
    ./configure -prefix=${ROOT_DIR}/libs/
    make
    make install
    popd
    popd
}

function check_glib2()
{
    pkg-config --exists glib-2.0

    if [ "$?" -ne "0" ]; then
        echo "glib2 is not installed."
	install_glib2
    fi
    
}

function check_mdbtools() {
    local mdbtool_bin=${ROOT_DIR}/libs/bin/mdb-export
    if [[ ! -e  ${mdbtool_bin} ]]; then
        echo "mdbtools not installed."Aa
        install_mdbtool
    fi
}
