#!/bin/bash

# Load common
source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/common

# Configure versions

PYTHON_VERSION="2.7.6"

# Setup dir references

# Try to guess the number of processors from /proc/cpuinfo.
if [ -f /proc/cpuinfo ]; then
    NUMBER_OF_PROCESSORS=$(grep -c ^processor /proc/cpuinfo)
else
    NUMBER_OF_PROCESSORS=1
fi

# Load functions
source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/build_python
source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/build_uwsgi

# check python
check_python
# virtual env
check_venv
# virtual uwsgi
check_uwsgi
# install requirement
install_requirements
