#!/bin/bash

function expand_env_vars() {
    local SRC=$1
    local DEST=$2
    cat $SRC | sed -f $OPENSHIFT_TMP_DIR/sed.script > $DEST
}

function copy_templates() {
    mkdir -p $CONFIG_DIR
    expand_env_vars $TEMPLATE_DIR/uwsgi.ini.tmpl $CONFIG_DIR/uwsgi.ini
    msg_info "Creating uWSGI config... done"

#    msg_info "Creating nginx config..."
#    expand_env_vars $TEMPLATE_DIR/nginx.conf.tmpl $ROOT_DIR/nginx/conf/nginx.conf
#    msg_info "Creating nginx config... done"
}

set -e

source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/common

BUILD_DIR=${OPENSHIFT_TMP_DIR}/build
NGINX_DIR=${OPENSHIFT_RUNTIME_DIR}/nginx/
PHP_DIR=${OPENSHIFT_RUNTIME_DIR}/php5/
TEMPLATE_DIR=${OPENSHIFT_REPO_DIR}/.openshift/tmpl
PHPMYADMIN_DIR=${OPENSHIFT_RUNTIME_DIR}/phpMyAdmin/

umask 077

mkdir -p ${BUILD_DIR}

echo "Pre-processing nginx config."
cp ${TEMPLATE_DIR}/nginx.conf.tmpl ${BUILD_DIR}/nginx.conf
perl -p -i -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' ${BUILD_DIR}/nginx.conf
cp ${BUILD_DIR}/nginx.conf ${NGINX_DIR}/conf/nginx.conf

echo "Pre-processing PHP-fpm config."
cp ${TEMPLATE_DIR}/php-fpm.conf.tmpl ${BUILD_DIR}/php-fpm.conf
perl -p -i -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' ${BUILD_DIR}/php-fpm.conf
cp ${BUILD_DIR}/php-fpm.conf ${PHP_DIR}/etc/php-fpm.conf

echo "Pre-processing phpmyadmin config."
cp ${TEMPLATE_DIR}/config.inc.php.tmpl ${BUILD_DIR}/config.inc.php
perl -p -i -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' ${BUILD_DIR}/config.inc.php
cp ${BUILD_DIR}/config.inc.php ${PHPMYADMIN_DIR}/config.inc.php

rm -rf ${BUILD_DIR}

#bash_profile=${OPENSHIFT_DATA_DIR}/.bash_profile
#echo "Copy bash profile."
#cp ${TEMPLATE_DIR}/bash_profile.tmpl ${bash_profile}

env | sed 's/[\%]/\\&/g;s/\([^=]*\)=\(.*\)/s%${\1}%\2%/' > $OPENSHIFT_TMP_DIR/sed.script

copy_templates
