#!/bin/bash

source $OPENSHIFT_REPO_DIR/.openshift/action_hooks/common

NGINX_PIDFILE=$OPENSHIFT_RUN_DIR/nginx.pid
if [ -f $NGINX_PIDFILE ]; then
    $OPENSHIFT_RUNTIME_DIR/nginx/sbin/nginx -s stop
fi

UWSGI_PIDFILE=$OPENSHIFT_RUN_DIR/uwsgi.pid
if [ -f $UWSGI_PIDFILE ]; then
    kill -QUIT $(cat $UWSGI_PIDFILE)
fi
